x-builder: &builder
  image: mkaczanowski/packer-builder-arm
  command: build raspios-lite.json
  volumes:
    - .:/app
    - /dev:/dev
  working_dir: /app
  privileged: true

services:
  lite64:
    <<: *builder
    environment:
      - IMG_URL=https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz
      - FILENAME=raspios-lite-arm64.img

  devenv:
    <<: *builder
    command: build raspios-lite-devenv.json
    environment:
      - IMG_URL=https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz
      - FILENAME=raspios-lite-arm64-devenv.img

  lite:
    <<: *builder
    environment:
      - IMG_URL=https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf-lite.img.xz
      - FILENAME=raspios-lite-armhf.img

  buster-lite64:
    <<: *builder
    command: build raspios-lite-buster.json
    environment:
      - IMG_URL=https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/2021-05-07-raspios-buster-arm64-lite.zip
      - FILENAME=raspios-lite-buster64-arm64.img

  # ubuntu:
  #   <<: *builder
  #   command: build ubuntu-server-arm64.json
  #   environment:
  #     - IMG_URL=https://cdimage.ubuntu.com/releases/24.04/release/ubuntu-24.04-preinstalled-server-arm64+raspi.img.xz
  #     - MD5_URL=https://cdimage.ubuntu.com/releases/24.04/release/SHA256SUMS
  #     - FILENAME=ubuntu-24.04-arm64.img
    


   