name: Build Images
"on":
  workflow_dispatch:
jobs:
  build-raspios-lite-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.18"
      - name: Check out repo code
        uses: actions/checkout@v2.3.4
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Fetch additional packages
        run: |-
          sudo apt-get update
          sudo apt-get install tree fdisk gdisk qemu-user-static libarchive-tools psmisc tar autoconf make
      - name: Get packer-build-arm plugin
        run: |-
          git clone https://github.com/mkaczanowski/packer-builder-arm plugin
          cd plugin
          go mod download
          go build
      - name: Build the image
        run: |-
          cp plugin/packer-builder-arm .
          sudo packer build raspios-lite-arm64.json | tee build.log || true
          grep "::BUILD::SUCCESS" build.log
          test -f raspios-lite-arm64-2022-04-04-arm64.img
      - uses: actions/upload-artifact@v4
        with:
          name: raspios-lite-arm64-2022-04-04-arm64
          path: raspios-lite-arm64-2022-04-04-arm64.img
  
